" bellator's vimrc

scriptencoding utf-8

"""""""""""""""""""""""""""""""""""""""
" 0. Load Plugin {{{
"""""""""""""""""""""""""""""""""""""""
" All the vim plugins, powered by 'vim-plug', are
" listed up in the separate file 'plugins.vim'.
" It is for making this vimrc could also work out-of-box
" even if not managed by dotfiles.
if filereadable(expand("\~/.vim/plugins.vim"))
    source \~/.vim/plugins.vim
endif

" }}}
"""""""""""""""""""""""""""""""""""""""
" 1. General Settings {{{
"""""""""""""""""""""""""""""""""""""""

syntax on
set nocompatible

" use path '~/.vim' even on non-unix machine
set runtimepath+=~/.vim

" add ~/.local/bin to $PATH
let $PATH .= ":" . expand("\~/.local/bin")

" basic displays
set number		    " show line numbers
set ruler

" input settings
set bs=indent,eol,start	    " allow backspaces over everything
set autoindent
set smartindent
set pastetoggle=<F8>

set nowrap
set textwidth=0             " disable automatic line breaking
" set cursorline

" tabsettings
set tabstop=8
set shiftwidth=4
set softtabstop=4

" tab navigation
set showtabline=2	    " always show tab pannel

set scrolloff=3

" search
set ignorecase		    " case-insensitive by default
set smartcase		    " case-sensitive if keyword contains both uppercase and lowercase
set incsearch
set hlsearch

" use spaces for tabbing, by default
set expandtab

" listchars for whitespaces
set list
set listchars=tab:»\ ,trail:·,extends:>,precedes:<

" wildmenu settings
set wildmenu
set wildmode=list:longest,full
set wildignore=*.swp,*.swo,*.class

" status line
set laststatus=2	    " show anytime

" native customized statusline, if airline is not available
" (this setting will be replaced afterwards by airline)
set statusline=%1*%{winnr()}\ %*%<\ %f\ %h%m%r%=%l,%c%V\ (%P)

" mouse behaviour
set mouse=nvc
if !has('nvim')
    " vim only (not in neovim)
    set ttymouse=xterm2
endif

" encoding and line ending settings
if !has('nvim')
    set encoding=utf-8
endif
set fileencodings=utf-8,cp949,latin1
set fileformats=unix,dos

" split and autocomplete settings
set splitbelow				    " preview window at bottom
set completeopt=menuone,preview,longest	    " show preview and pop-up menu

" no fucking swap and backup files
set noswapfile
set nobackup

" set miscellaneous
set showmode
set showcmd

" set visualbell
set history=1000
set undolevels=1000
" }}}

autocmd FileType scala setlocal ts=8 sts=2 sw=2

filetype plugin on
filetype indent on

""""""""""""""""""""""""""""""
" 6. Plugin Setting {{{
""""""""""""""""""""""""""""""

" vim-easy-algin {{{

" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
"------------------------------------------------------------------}}}
" }}}
